# Generated by Django 4.2 on 2023-04-28 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_key', models.CharField(max_length=40, verbose_name='Chave')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.CharField(blank=True, max_length=1000, verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to='arquivo/')),
                ('posicao', models.IntegerField(blank=True, default=0, verbose_name='Posição')),
            ],
            options={
                'ordering': ['posicao'],
            },
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.CharField(blank=True, max_length=400, verbose_name='Descrição')),
                ('posicao', models.IntegerField(blank=True, default=0, verbose_name='Posição')),
                ('texto', models.TextField(verbose_name='Conteúdo do Tópico')),
                ('fixo', models.BooleanField(default=False, verbose_name='Fixo')),
            ],
            options={
                'ordering': ['-fixo', 'posicao', '-criado'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_key', models.CharField(editable=False, max_length=40, verbose_name='Chave')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.CharField(blank=True, max_length=400, verbose_name='Descrição')),
                ('posicao', models.IntegerField(blank=True, default=0, verbose_name='Posição')),
            ],
            options={
                'ordering': ['posicao'],
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_key', models.CharField(editable=False, max_length=40, verbose_name='Chave')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.CharField(blank=True, max_length=400, verbose_name='Descrição')),
                ('posicao', models.IntegerField(blank=True, default=0, verbose_name='Posição')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategoria', to='forum.categoria')),
            ],
            options={
                'ordering': ['posicao'],
            },
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_key', models.CharField(editable=False, max_length=40, verbose_name='Chave')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('texto', models.TextField(verbose_name='Conteúdo do Tópico')),
                ('fixo', models.BooleanField(default=False, verbose_name='Fixo')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topico', to='forum.subcategoria')),
            ],
            options={
                'ordering': ['-fixo', '-criado'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_key', models.CharField(editable=False, max_length=40, verbose_name='Chave')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('comentario', models.TextField(verbose_name='Comentário')),
                ('posicao', models.IntegerField(blank=True, default=0, verbose_name='Posição')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='forum.topico')),
            ],
            options={
                'ordering': ['-criado', 'posicao'],
            },
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['id'], name='id_comentario'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='topico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivo', to='forum.topico'),
        ),
        migrations.AddIndex(
            model_name='topico',
            index=models.Index(fields=['id'], name='id_topico'),
        ),
    ]
